plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "lib/axe/cuprite/vendor/**/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/PredicatePrefix:
  AllowedMethods:
    - is_a?
    - does_not_match?

Naming/PredicateMethod:
  AllowedMethods:
    - ensure_injected!
    - try_add_script_tag

Naming/FileName:
  Exclude:
    - lib/axe-cuprite.rb
